baseURL = "https://example.org/"
languageCode = 'en-us'
title = "Antonio Thomas Worley"
theme = "hugo-PaperMod"

[outputs]
home = [ "html", "RSS", "JSON" ]

[params.homeInfoParams]


[[menu.main]]
name = "CV"
url = "http://localhost:1313/cv"
weight = "5"

[[menu.main]]
name = "Archives"
url = "http://localhost:1313/archives"
weight = "5"

[[menu.main]]
name = "Search Page"
url = "http://localhost:1313/Searchpage"
weight = "5"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      attribute = true