baseURL = "https://example.org/"
languageCode = 'en-us'
title = "Antonio Thomas Worley"
theme = "hugo-PaperMod"

[outputs]
home = [ "html", "RSS", "JSON" ]

[params.homeInfoParams]

[[menu.main]]
name = "Blog"
url = "http://localhost:1313/blog"
weight = "5"

[[menu.main]]
name = "CV"
url = "http://localhost:1313/cv"
weight = "5"

[[menu.main]]
name = "Archives"
url = "http://localhost:1313/archives"
weight = "5"

[[menu.main]]
name = "Searchpage"
url = "http://localhost:1313/Searchpage"
wegith = "5"